\pagebreak
\subsection{\Sexpr{gene.names[{{current.index}}]}}

<<Single_gene_metaanalysis_load_data_{{current.index}}, include=FALSE, cache=TRUE>>=
# Remove patients with NA values for that gene

esets.with.gene <- esets.rfs[sapply(esets.rfs, function(x) entrez.ids[{{current.index}}] %in% fData(x)$EntrezGene.ID)]
esets.with.gene <- lapply(esets.with.gene, function(eset) {
  current.entrez.id.index <- which(fData(eset)$EntrezGene.ID == entrez.ids[{{current.index}}])
  eset.toreturn <- eset[,!is.na(exprs(eset))[current.entrez.id.index,]]
  return(eset.toreturn)
  })

survival.df.list <- lapply(esets.with.gene, function(eset) {
  index <- which(fData(eset)$EntrezGene.ID == entrez.ids[{{current.index}}])
  if(length(index) != 1) {
    stop("Found a different number than one matching Entrez ID")
  }
  expression.values <- exprs(eset)[index,]
  expression.quantiles <- cut(expression.values, breaks=quantile(expression.values, probs=c(0,0.5,1)), include.lowest=TRUE)
  
  levels(expression.quantiles) <- c("Low", "High")
  
  #Re-order so high comes first
  #expression.quantiles <- factor(expression.quantiles, levels=rev(levels(expression.quantiles)))
  
  colnames.to.keep <- c("days_to_tumor_recurrence", "recurrence_status")
    if("dmfs_status" %in% colnames(pData(eset))) {
      colnames.to.keep <- c(colnames.to.keep, "dmfs_days", "dmfs_status")
    }
  
  if("data.source" %in% colnames(pData(eset))) {
    colnames.to.keep <- c("data.source", colnames.to.keep)
  }
  
  survival.data <- pData(eset)[colnames.to.keep]
  survival.data[[paste0(rownames(exprs(eset))[index], ".expression")]] <- expression.values
  survival.data[[paste0(rownames(exprs(eset))[index], ".quantile")]] <- expression.quantiles
  
  if("dmfs_status" %in% colnames(pData(eset))) {
      survival.data$recurrence_status <- survival.data$recurrence_status == "recurrence"
      survival.data$dmfs_status <- survival.data$dmfs_status == "recurrence"
      
      use.dmfs.logical <- is.na(survival.data$days_to_tumor_recurrence) & is.na(survival.data$recurrence_status) & !is.na(survival.data$dmfs_days) & !is.na(survival.data$dmfs_status)
      
      survival.data$days_to_tumor_recurrence[use.dmfs.logical] <- survival.data$dmfs_days[use.dmfs.logical]
      survival.data$recurrence_status[use.dmfs.logical] <- survival.data$dmfs_status[use.dmfs.logical]
      
      survival.data$dmfs_days <- NULL
      survival.data$dmfs_status <- NULL
  }
  
  # Rename last two columns
  colnames(survival.data)[colnames(survival.data) == "days_to_tumor_recurrence"] <- "days_to_event"
  colnames(survival.data)[colnames(survival.data) == "recurrence_status"] <- "event_status"
  
  survival.data$years_to_event <- survival.data$days_to_event / days.per.year
  survival.data$days_to_event <- NULL
  
  surv.cens.obj <- survcomp::censor.time(survival.data$years_to_event, survival.data$event_status, time.cens=10)
  survival.data$years_to_event <- surv.cens.obj$surv.time.cens
  survival.data$event_status <- surv.cens.obj$surv.event.cens
  
  return(survival.data)
})

@



<<singlegene_metaanalysis_forestplot_{{current.index}}, fig.width=5, fig.height=7, out.width="0.5\\textwidth", cache=TRUE>>=
xlim=c(-4.5,3)
alim=c(-3,3)
at=log(c(.25, 0.5, 1, 2, 4))

hr.stat.objects <- lapply(survival.df.list, function(survival.df) {
    survcomp::hazard.ratio(x=survival.df[[paste0("geneid.", entrez.ids[{{current.index}}], ".quantile")]], surv.time=survival.df$years_to_event, surv.event=survival.df$event_status)
    })

hr.stat.vals <- sapply(hr.stat.objects, function(x) x$coef)
hr.stat.se <- sapply(hr.stat.objects, function(x) x$se)  
hr.rma.random <- rma(hr.stat.vals, sei=hr.stat.se, method="REML", slab=names(survival.df.list))

forest(hr.rma.random, xlab="Hazard Ratio", atransf=exp, refline = 0, annotate=FALSE, addfit=FALSE, ylim=c(-2.5,length(hr.stat.vals) + 3), at=log(c(0.25,0.5,1,2,4)), xlim=xlim, alim=alim, main=paste0("Meta-analysis: ", gene.names[{{current.index}}]))
abline(h=0, lwd=1)
addpoly(hr.rma.random, mlab="Random Effects Estimate", row=-1, atransf=exp, annotate=TRUE)

hr.matrix[gene.names[{{current.index}}],names(hr.stat.vals)] <- hr.stat.vals
hr.rma.objs[[gene.names[{{current.index}}]]] <- hr.rma.random
@

<<survival_curve_{{current.index}}, fig.width=5, fig.height=5.5, out.width="0.5\\textwidth", cache=TRUE>>=
survival.df.combined <- do.call(rbind, survival.df.list)

survival.df.combined$surv.obj <- Surv(time = survival.df.combined$years_to_event, event = survival.df.combined$event_status)

main.title = paste0("Pooled survival: ", gene.names[{{current.index}}])
km.coxph.plot(as.formula(paste0("surv.obj ~ geneid.", entrez.ids[{{current.index}}], ".quantile")), survival.df.combined, x.label="Time (years)", y.label = "Recurrence-free survival", main.title=main.title, show.n.risk = FALSE, leg.text = levels(survival.df.combined[[paste0("geneid.", entrez.ids[{{current.index}}], ".quantile")]]), leg.pos="topright", leg.bty="n", leg.inset=0, n.risk.cex=0.85, cex=0.4, o.text="")

o.text <- paste(sprintf("HR: %.3f [%.3f,%.3f]\n", exp(hr.rma.random$b), exp(hr.rma.random$ci.lb), exp(hr.rma.random$ci.ub)), sprintf("p = %.1E", hr.rma.random$pval))
text(0,0.05, o.text, cex=0.85, pos=4)

hr.random.effects.pval[{{current.index}}] <- hr.rma.random$pval
# create.forest.plot returns log2(HR)
hr.random.effects.estimate[{{current.index}}] <- exp(as.vector(hr.rma.random$b))
hr.random.effects.lower[{{current.index}}] <- exp(hr.rma.random$ci.lb)
hr.random.effects.upper[{{current.index}}] <- exp(hr.rma.random$ci.ub)
@


<<compute_d_index_{{current.index}}, cache=TRUE>>=
d.index.stat.objects <- lapply(survival.df.list, function(survival.df) {
    survcomp::D.index(x=survival.df[[paste0("geneid.", entrez.ids[{{current.index}}], ".expression")]], surv.time=survival.df$years_to_event, surv.event=survival.df$event_status)
    })

d.index.stat.vals <- sapply(d.index.stat.objects, function(x) x$coef)
d.index.stat.se <- sapply(d.index.stat.objects, function(x) x$se)  
d.index.rma.random <- rma(d.index.stat.vals, sei=d.index.stat.se, method="REML", slab=names(survival.df.list))

d.index.matrix[gene.names[{{current.index}}],names(d.index.stat.vals)] <- d.index.stat.vals
d.index.rma.objs[[gene.names[{{current.index}}]]] <- d.index.rma.random

d.index.random.effects.pval[{{current.index}}] <- d.index.rma.random$pval
# create.forest.plot returns log2(d.index)
d.index.random.effects.estimate[{{current.index}}] <- exp(as.vector(d.index.rma.random$b))
d.index.random.effects.lower[{{current.index}}] <- exp(d.index.rma.random$ci.lb)
d.index.random.effects.upper[{{current.index}}] <- exp(d.index.rma.random$ci.ub)

survival.sample.sizes[{{current.index}}] <- sum(sapply(survival.df.list, nrow))
@

\noindent Random effects model:

\Sexpr{sprintf("HR: %.02f [%.02f, %.02f], p = %.1E", exp(as.vector(hr.rma.random$b)), exp(hr.rma.random$ci.lb), exp(hr.rma.random$ci.ub), hr.rma.random$pval)}

\Sexpr{sprintf("D-Index: %.02f [%.02f, %.02f], p = %.1E", exp(as.vector(d.index.rma.random$b)), exp(d.index.rma.random$ci.lb), exp(d.index.rma.random$ci.ub), d.index.rma.random$pval)}